# Azure Pipeline for ASP.NET project -- build, test, publish, provision, & deploy
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
# https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core

trigger:
- master

variables:
  tag: '$(Build.BuildId)'
  dotnetFramework: "net5.0"
  dotnetRuntimeVersion: "5.0.x"
  projectName: "ContosoUniversity"
  dbContext: "SchoolContext"

stages:
- stage: Build
  pool:
    vmImage: "ubuntu-latest"
  variables:
    solution: "**/*.sln"
    buildPlatform: "AnyCPU"
    buildConfiguration: "Release"
    scriptName: "migrations.sql"
  jobs:
  # ------------------------ Environment Setup Steps ------------------------
  # Each job receives its own machine; installed tools must persist across all jobs/steps
  - job: Build
    steps:
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer
    - task: UseDotNet@2
      displayName: "Install .NET SDK"
      inputs:
        version: "$(dotnetRuntimeVersion)"
        packageType: runtime
    
    # Omit '--version' here and let SDK determine EF package
    - script: dotnet tool install --global dotnet-ef
      displayName: "Install .NET EF"

    # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/nuget
    - task: NuGetToolInstaller@1
      displayName: "Install NuGet"

    # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget
    - task: NuGetCommand@2
      displayName: "Restore NuGet package dependencies"
      inputs:
        restoreSolution: "$(solution)"

        
    # ------------------------ Build Steps ------------------------
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli
    - task: DotNetCoreCLI@2
      displayName: "Build .NET: $(buildConfiguration)"
      inputs:
        command: build
        arguments: >-
          --framework $(dotnetFramework)
          --configuration $(buildConfiguration)
          --nologo


    # ------------------------ Test Steps ------------------------
    - task: DotNetCoreCLI@2
      displayName: "Test .NET: $(buildConfiguration)"
      inputs:
        command: test
        projects: "**/*Tests/*.csproj"
        arguments: >-
          --framework $(dotnetFramework)
          --configuration $(buildConfiguration)
          --nologo

        
    # ------------------------ Artifact Staging Steps ------------------------
    # Provides zip file for deployment to app service
    # Can't output to specific filename but still few steps than ArchiveFiles@2 + CopyFiles@2
    - task: DotNetCoreCLI@2
      displayName: "Stage build output"
      inputs:
        command: publish
        publishWebProjects: True
        # https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish#options
        arguments: >-
          --framework $(dotnetFramework)
          --configuration $(buildConfiguration)
          --output $(Build.ArtifactStagingDirectory)
          --nologo
        zipAfterPublish: True

    # https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet
    # https://docs.microsoft.com/en-us/ef/core/cli/dotnet#common-options
    - script: >-
        dotnet ef migrations script
        --framework $(dotnetFramework)
        --configuration $(buildConfiguration)
        --startup-project $(projectName)/$(projectName).csproj
        --output $(Build.ArtifactStagingDirectory)/$(scriptName)
        --idempotent
      displayName: "Stage SQL migration script"
      
    # Provides ARM (Azure Resource Manager) files
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files
    - task: CopyFiles@2
      displayName: "Stage ARM files"
      inputs:
        contents: "**/bin/**/ArmTemplates/**/azuredeploy*.json"
        targetFolder: "$(Build.ArtifactStagingDirectory)"
        flattenFolders: True

      
    # ------------------------ Artifact Publish Steps ------------------------
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts
    - task: PublishBuildArtifacts@1
      displayName: "Publish build artifact: drop"
      inputs:
        pathtoPublish: "$(Build.ArtifactStagingDirectory)" 
        artifactName: "drop"
        