# Azure Pipeline for ASP.NET project -- build, test, publish, provision, & deploy
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
# https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core

trigger:
- master

variables:
  tag: '$(Build.BuildId)'
  dotnetFramework: "net5.0"
  dotnetRuntimeVersion: "5.0.x"
  projectName: "ContosoUniversity"
  dbContext: "SchoolContext"

stages:
- stage: Build
  pool:
    vmImage: "ubuntu-latest"
  variables:
    solution: "**/*.sln"
    buildPlatform: "AnyCPU"
    buildConfiguration: "Release"
    artifactApplicationName: "app.zip"
    artifactMigrationName: "migrations.sql"
  jobs:
  # ------------------------ Environment Setup Steps ------------------------
  # Each job receives its own machine; installed tools must persist across all jobs/steps
  - job: Build
    steps:
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer
    - task: UseDotNet@2
      displayName: "Install .NET SDK"
      inputs:
        version: "$(dotnetRuntimeVersion)"
        packageType: runtime
    
    # Omit '--version' here and let SDK determine EF package
    - script: dotnet tool install --global dotnet-ef
      displayName: "Install .NET EF"

    # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/nuget
    - task: NuGetToolInstaller@1
      displayName: "Install NuGet"

    # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget
    - task: NuGetCommand@2
      displayName: "Restore NuGet package dependencies"
      inputs:
        restoreSolution: "$(solution)"

        
    # ------------------------ Build Steps ------------------------
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli
    - task: DotNetCoreCLI@2
      displayName: "Build .NET: $(buildConfiguration)"
      inputs:
        command: build
        arguments: "--configuration $(buildConfiguration)"


    # ------------------------ Test Steps ------------------------
    - task: DotNetCoreCLI@2
      displayName: "Test .NET: $(buildConfiguration)"
      inputs:
        command: test
        projects: "**/*Tests/*.csproj"
        arguments: "--configuration $(buildConfiguration)"

        
    # ------------------------ Artifact Staging Steps ------------------------
    # Provides zip file for web app service
    - task: DotNetCoreCLI@2
      displayName: "Stage build output"
      inputs:
        command: publish
        publishWebProjects: True
        # https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish#options
        # arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"
        arguments: >-
          --framework $(dotnetFramework)
          --configuration $(buildConfiguration)
          --output $(Build.ArtifactStagingDirectory)/$(artifactApplicationName)
        zipAfterPublish: True

    # https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet
    # https://docs.microsoft.com/en-us/ef/core/cli/dotnet#common-options
    - script: >-
        dotnet ef migrations script
        --framework $(dotnetFramework)
        --configuration $(buildConfiguration)
        --startup-project $(projectName)/$(projectName).csproj
        --output $(Build.ArtifactStagingDirectory)/$(artifactMigrationName)
        --idempotent
      displayName: "Stage SQL migration script"

      
    # ------------------------ Artifact Publish Steps ------------------------
    - task: PublishBuildArtifacts@1
      displayName: "Publish build artifact: drop"
      inputs:
        pathtoPublish: "$(Build.ArtifactStagingDirectory)" 
        artifactName: "drop"
        